apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: codegen-mar14-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-mar14-1
  name: codegen-mar14-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
